#!/bin/bash

DOMAIN_REGEX="^([a-z0-9]([-a-z0-9]*[a-z0-9])?.)+((a[cdefgilmnoqrstuwxz]|aero|arpa)|(b[abdefghijmnorstvwyz]|biz)|(c[acdfghiklmnorsuvxyz]|cat|com|coop)|d[ejkmoz]|(e[ceghrstu]|edu)|f[ijkmor]|(g[abdefghilmnpqrstuwy]|gov)|h[kmnrtu]|(i[delmnoqrst]|info|int)|(j[emop]|jobs)|k[eghimnprwyz]|l[abcikrstuvy]|(m[acdghklmnopqrstuvwxyz]|mil|mobi|museum)|(n[acefgilopruz]|name|net)|(om|org)|(p[aefghklmnrstwy]|pro)|qa|r[eouw]|s[abcdeghijklmnortvyz]|(t[cdfghjklmnoprtvwz]|travel)|u[agkmsyz]|v[aceginu]|w[fs]|y[etu]|z[amw])$"

if [[ -z "$1" ]]; then
    echo "Ops, você precisa passar um domínio válido como argumento!"
    exit 1
fi

if [[ $1 =~ $DOMAIN_REGEX ]]; then
  echo "As informações sobre o domínio serão passadas para um novo arquivo: '$1.info'"
else
  echo "Ops, argumento inválido!"
  exit 1
fi

cd ~

if [[ -d domains_info ]]; then
    echo "O arquivo '$1.info' será guardado em: ~/domains_info"
else
    echo "Um novo diretório será criado para guardar o arquivo '$1.info' em: ~/domains_info"
    mkdir domains_info
fi

cd domains_info
whois $1 > "$1.info"
chmod 444 "$1.info"

echo "As 10 primeiras linhas do arquivo '$1.info':"
head $1.info
